# Generated by Django 2.2.24 on 2021-09-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=60)),
            ],
        ),
    ]
